# Generated by Django 5.0.6 on 2024-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
