# Generated by Django 5.0.6 on 2024-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_planta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
